import type { NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';

const getArtists = async () => {
  const { data } = await axios.get(
    `http://localhost:3000/api/artists`
    );
  
  return JSON.parse(data)
}


export async function getServerSideProps(){
  const data = await getArtists();

  return {
    props: { data }
  }
}


const Home: NextPage = ({ data }: any) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Artpoint App</title>
        <meta name="description" content="Generated by younss" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-300 p-5 md:p-10 lg:p-20">
        <h1 className="text-center text-3xl font-bold">{data?.title}</h1>
        <p className="text-center text-xl">{data?.text}</p>

        <div className="grid gap-4 sm:grid-col sm:grid-row md:grid-cols-2 md:grid-rows-2 p-10 rounded-lg shadow-md">
          {data?.length === 0 ? (
            <div>...Loading</div>
          ) : (
            data?.artists.map((artist: any) => (
              <Link href={`artists/${artist.slug}`} key={artist.id}>
                <div className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100">
                  <h2 className="text-xl font-bold">{artist.name}</h2>
                  <div className="mt-4 mb-10">
                    <p className="text-gray-600">Slug : {artist.slug}</p>
                  </div>

                  <div>
                    <h3 className="font-normal text-gray-700">Description :</h3>
                    {artist.texts.map((text: any) => (
                      <div key={text.id}>
                        <p className="text-neutral-500">{text.body}</p>
                      </div>
                    ))}
                  </div>
                  <button className="bg-orange-400 py-3 px-8 mt-4 rounded text-sm font-semibold hover:bg-opacity-75">
                    Voir l'artiste
                  </button>
                </div>
              </Link>
            ))
          )}
        </div>
      </main>
    </>
  )
}

export default Home


